import notification
import weatherLED
from time import sleep

weatherLED.weather_color(800)
notification.speak('clear')
sleep(4)
weatherLED.weather_color(801)
notification.speak('clouds')
sleep(4)
weatherLED.weather_color(300)
notification.speak('drizzle')
sleep(4)
weatherLED.weather_color(500)
notification.speak('rain')
sleep(4)
weatherLED.weather_color(200)
notification.speak('thunderstorm')
sleep(4)
weatherLED.weather_color(600)
notification.speak('snow')
sleep(4)
weatherLED.weather_color(701)
notification.speak('mist or fog')
sleep(4)
weatherLED.weather_color(761)
notification.speak('dust')
sleep(4)
weatherLED.weather_color(781)
notification.speak('tornado')
sleep(4)
weatherLED.weather_color(0)